name: Build

on: [push, pull_request]

jobs:

  build_linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install libelf-dev binutils-dev
      - run: make
